# Lift Generated by Wings on a Mass vs its Weight

from math import sin, pi, cos
from numpy import arange, array 
from matplotlib import pyplot as plt 

m = eval(input('Please enter the mass of the object (kg)\n'))

v = eval(input('Please enter the velocity of the object wrt air (m/s)\n')) 
theta = (pi/180)*eval(input('Angle of attack (degrees)\n')) 
P0 = 101325 #Pa 
T0 = 288.15 #K
B = 0.00650 #K/m B 
g = 9.81 #m/s^2 
R = 287 #J/KgK 
#p = eval(input('Precision to calculate surface area\n'))

def rho(z): 
    numerator = P0*((1-((B*z)/T0))**(g/(R*B)))
    denominator = R*(T0-(B*z)) 
    rho = numerator/denominator
    return rho

while True:
    z= eval(input('Please enter the altitude(m)\n'))
    if z > 11000:
        print('Please input an altitude less that 11,000 m²')
        continue
    else:
        print('Air density', rho(z), 'Kg/m^3') 
        break

Sar = (m*g)/(rho(z)*(v**2)*sin(theta) *cos(theta))
print(Sar)